export const docentes = [
  {
    id: 1,
    nombre: 'Dr. Juan Pérez',
    titulo: 'Profesor Titular',
    email: 'juan.perez@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=160&h=160&fit=crop&q=80',
    formacion: ['Ph.D. en Ciencias Computacionales', 'M.Sc. en Tecnología de la Información'],
    experiencia: ['Investigador en Proyectos TIC', 'Consultor en IT'],
    proyectos: ['Inteligencia Artificial y Educación'],
    asignaturas: ['Programación Avanzada', 'Bases de Datos'],
  },
  {
    id: 2,
    nombre: 'Dra. María González',
    titulo: 'Profesora Asociada',
    email: 'maria.gonzalez@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&h=160&fit=crop&q=80',
    formacion: ['Ph.D. en Ingeniería de Software', 'M.Sc. en Sistemas Distribuidos'],
    experiencia: ['Desarrolladora Senior en empresa tecnológica', 'Consultora en transformación digital'],
    proyectos: ['Sistemas de Gestión Académica', 'Seguridad Informática'],
    asignaturas: ['Ingeniería de Software', 'Redes de Computadoras'],
  },
  {
    id: 3,
    nombre: 'Mg. Carlos Rodríguez',
    titulo: 'Profesor Auxiliar',
    email: 'carlos.rodriguez@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&h=160&fit=crop&q=80',
    formacion: ['M.Sc. en Ciencia de Datos', 'Ing. en Sistemas Informáticos'],
    experiencia: ['Analista de datos en sector público', 'Docente universitario por 8 años'],
    proyectos: ['Machine Learning aplicado a la educación'],
    asignaturas: ['Estadística Computacional', 'Minería de Datos'],
  },
  {
    id: 4,
    nombre: 'Dra. Ana Martínez',
    titulo: 'Profesora Titular',
    email: 'ana.martinez@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&h=160&fit=crop&q=80',
    formacion: ['Ph.D. en Redes de Computadoras', 'M.Sc. en Telecomunicaciones'],
    experiencia: ['Consultora en infraestructura de redes', 'Investigadora en proyectos SENESCYT'],
    proyectos: ['Redes definidas por software (SDN)', 'Internet de las Cosas en entornos rurales'],
    asignaturas: ['Redes de Computadoras', 'Telecomunicaciones'],
  },
  {
    id: 5,
    nombre: 'Ing. Luis Herrera',
    titulo: 'Profesor Auxiliar',
    email: 'luis.herrera@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&q=80',
    formacion: ['M.Sc. en Desarrollo de Software', 'Ing. en Sistemas'],
    experiencia: ['Desarrollador Full Stack por 10 años', 'Tech Lead en empresa de software'],
    proyectos: ['Aplicaciones web progresivas', 'Plataformas e-learning'],
    asignaturas: ['Programación Web', 'Desarrollo de Aplicaciones Móviles'],
  },
  {
    id: 6,
    nombre: 'Mg. Sofía Cevallos',
    titulo: 'Profesora Asociada',
    email: 'sofia.cevallos@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=160&h=160&fit=crop&q=80',
    formacion: ['M.Sc. en Ciberseguridad', 'Ing. en Sistemas Computacionales'],
    experiencia: ['Auditora de seguridad informática', 'Consultora en protección de datos'],
    proyectos: ['Seguridad en aplicaciones web', 'Gestión de identidades digitales'],
    asignaturas: ['Seguridad Informática', 'Ethical Hacking'],
  },
  {
    id: 7,
    nombre: 'Dr. Roberto Parrales',
    titulo: 'Profesor Titular',
    email: 'roberto.parrales@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&h=160&fit=crop&q=80',
    formacion: ['Ph.D. en Inteligencia Artificial', 'M.Sc. en Visión por Computadora'],
    experiencia: ['Investigador en laboratorio de IA', 'Asesor tecnológico del sector público'],
    proyectos: ['Reconocimiento facial aplicado', 'Automatización con visión artificial'],
    asignaturas: ['Inteligencia Artificial', 'Visión por Computadora'],
  },
  {
    id: 8,
    nombre: 'Mg. Valeria Torres',
    titulo: 'Profesora Auxiliar',
    email: 'valeria.torres@universidad.edu.ec',
    foto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=160&h=160&fit=crop&q=80',
    formacion: ['M.Sc. en Gestión de Proyectos TI', 'Ing. en Informática'],
    experiencia: ['Project Manager certificada PMP', 'Coordinadora de proyectos en ONG tecnológica'],
    proyectos: ['Metodologías ágiles en educación', 'Gestión del cambio digital'],
    asignaturas: ['Gestión de Proyectos', 'Metodologías Ágiles'],
  },
]

export type Docente = typeof docentes[0]

export const noticias = [
  {
    id: 1,
    titulo: 'Convocatoria a Congreso TIC 2026',
    categoria: 'Eventos',
    fecha: '1 Abr 2026',
    resumen: 'No te pierdas el evento anual de Tecnologías de la Información. Inscripciones abiertas.',
    imagen: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=900&q=80',
    contenido: [
      'El Congreso TIC 2026 es el evento más importante del año para la comunidad de Tecnologías de la Información de la UNESUM. Este año contará con la participación de expertos nacionales e internacionales en áreas como Inteligencia Artificial, Ciberseguridad y Transformación Digital.',
      'Las inscripciones están abiertas hasta el 20 de abril de 2026. Los estudiantes de la carrera tienen acceso gratuito presentando su carnet universitario vigente.',
      'El evento se realizará en el auditorio principal de la universidad los días 5 y 6 de mayo de 2026, de 8h00 a 17h00.',
    ],
  },
  {
    id: 2,
    titulo: 'Nuevas becas disponibles para estudiantes de TI',
    categoria: 'Académico',
    fecha: 'Mar 2026',
    resumen: 'La carrera ofrece becas de excelencia académica para el período 2026.',
    imagen: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=900&q=80',
    contenido: [
      'La Carrera de Tecnologías de la Información anuncia la apertura de 10 becas de excelencia académica para estudiantes destacados del período lectivo 2026.',
      'Los requisitos incluyen un promedio mínimo de 8.5, no haber reprobado ninguna materia y estar matriculado en al menos 4 asignaturas. Las becas cubren el 50% del costo de matrícula.',
      'Las solicitudes deben ser entregadas en la secretaría de la carrera hasta el 15 de abril de 2026 con los documentos requeridos.',
    ],
  },
  {
    id: 3,
    titulo: 'Publicación de resultados del proyecto IA Educativa',
    categoria: 'Investigación',
    fecha: 'Feb 2026',
    resumen: 'El equipo de investigación presenta los resultados del proyecto de Inteligencia Artificial aplicada a la educación.',
    imagen: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=900&q=80',
    contenido: [
      'El grupo de investigación de la Carrera de Tecnologías de la Información presenta los resultados del proyecto "Inteligencia Artificial Educativa", desarrollado durante el período 2025-2026.',
      'El proyecto demostró que el uso de sistemas de tutoría inteligente mejora el rendimiento académico de los estudiantes en un 35% en comparación con métodos tradicionales de enseñanza.',
      'Los resultados han sido publicados en la Revista Latinoamericana de Tecnología Educativa y serán presentados en el Congreso TIC 2026.',
    ],
  },
]

export type Noticia = typeof noticias[0]
